#!/bin/bash

set -eu

umask 077
cp /etc/letsencrypt/live/irc.somdomato.com/fullchain.pem /etc/ergo/
cp /etc/letsencrypt/live/irc.somdomato.com/privkey.pem /etc/ergo/

cp /etc/letsencrypt/live/irc.somdomato.com/fullchain.pem /etc/soju/
cp /etc/letsencrypt/live/irc.somdomato.com/privkey.pem /etc/soju/

chown ergo:ergo /etc/ergo/*.pem
chown soju:soju /etc/soju/*.pem

systemctl reload somdomato-ergo.service
systemctl reload somdomato-soju.service
