# 1 = Debug; 2 = Info; 3 = Warn;
logLevel = 3

# Enable the built in identd server (listens on port 113)
identd = false

# The name of this gateway as reported in WEBIRC to IRC servers
gateway_name = "webircgateway"

# A secret string used for generating client JWT tokens. Do not share this!
secret = ""

# Send the server a quit message when the client is closed
send_quit_on_client_close = "Client closed"

[clients]
# %i = hex-encoded IP, %h = hostname, %n = nick
username = "%i"
realname = "Rádio Som do Mato"

# The websocket / http server (nginx proxies /webirc here)
[server.1]
bind = "127.0.0.1"
port = 8067

[fileserving]
enabled = false

[transports]
websocket
kiwiirc

# Websites allowed to connect
[allowed_origins]
*://chat.somdomato.com
*://irc.somdomato.com
*://somdomato.com

# Whitelisted reverse proxies (client IPs read from X-Forwarded-For)
[reverse_proxies]
127.0.0.0/8
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
"::1/128"
"fd00::/8"

# Upstream Ergo IRC server
[upstream.1]
hostname = "127.0.0.1"
port = 6667
tls = false
timeout = 5
throttle = 2
