---
- name: Preparar o ambiente para o Ergo e Gamja
  hosts: all
  become: true
  remote_user: root

  tasks:
    - name: Garante que o grupo "ergo" exista
      ansible.builtin.group:
        name: ergo
        state: present

    - name: Adicionar o usuário e grupo "ergo"
      ansible.builtin.user:
        name: ergo
        group: ergo

    # Nginx
    - name: Copiar os arquivos de configuração dos sites do Nginx
      ansible.builtin.copy:
        src: "etc/nginx/sites.d/{{ item }}"
        dest: "/etc/nginx/sites.d/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      with_items:
        - "51-irc.somdomato.com.conf"
        - "51-gamja.somdomato.com.conf"

    # Systemd
    - name: Alterar as unidades do systemd
      ansible.builtin.copy:
        src: "etc/systemd/system/somdomato-ergo.service"
        dest: "/etc/systemd/system/somdomato-ergo.service"
        owner: root
        group: root
        mode: "0644"

    - name: Reiniciar as unidades do systemd
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
        enabled: true
        daemon_reload: true
      with_items:
        - "somdomato-ergo.service"
        - "nginx.service"
